
# Manipulación de Datos Numéricos con Python y NumPy

## ¿Qué es NumPy?

[NumPy](https://numpy.org/doc/stable/index.html) significa numerical Python. Es la base de todo tipo de computación científica y numérica en Python.

## ¿Por qué usar NumPy?
Puedes realizar cálculos numéricos usando solo Python. Al principio, podrías pensar que Python es rápido, pero cuando tus datos crecen en tamaño, empezarás a notar que se vuelve más lento.

Una de las principales razones para usar NumPy es que es rápido. Detrás de escena, el código está optimizado para ejecutarse en C, otro lenguaje de programación que puede realizar operaciones mucho más rápido que Python.

Lo mejor de todo es que no necesitas saber C para aprovechar esta ventaja. Puedes escribir tus cálculos numéricos en Python usando NumPy y beneficiarte de su velocidad.

Si tienes curiosidad sobre qué causa esta mejora de rendimiento, se debe a un proceso llamado [vectorización](https://en.wikipedia.org/wiki/Vectorization). La vectorización busca realizar cálculos evitando los bucles, ya que estos pueden convertirse en cuellos de botella.

NumPy logra la vectorización mediante un proceso llamado [broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#module-numpy.doc.broadcasting).

## ¿Qué cubre este notebook?

La biblioteca NumPy es muy poderosa. Sin embargo, no es necesario memorizar todo. En lugar de eso, este notebook se enfoca en los conceptos principales de NumPy y el tipo de dato **ndarray**.

Puedes pensar en el tipo ndarray como un arreglo de números muy flexible.

Más específicamente, veremos:

* Tipos de datos y atributos en NumPy
* Creación de arreglos
* Visualización de arreglos y matrices (indexación)
* Manipulación y comparación de arreglos
* Ordenamiento de arreglos
* Casos de uso (ejemplos de cómo convertir cosas en números)

Después de revisar este notebook, tendrás el conocimiento base de NumPy que necesitas para seguir avanzando.


## ¿Dónde puedo obtener ayuda?
Si te quedas atascado o piensas en algo que te gustaría hacer y que este notebook no cubre, ¡no te preocupes!
Los pasos recomendados que puedes seguir son:


1. **Inténtalo tú mismo** – Tu primer paso debería ser usar lo que ya sabes e intentar encontrar la respuesta por tu cuenta (equivocarse es parte del proceso). Si tienes dudas, ejecuta tu código.


2. **Búscalo** – Si intentarlo por tu cuenta no funciona, probablemente alguien más haya intentado hacer algo similar. Intenta buscar tu problema en los siguientes lugares (ya sea usando un buscador o directamente):

    - [Documentación oficial de NumPy](https://numpy.org/doc/stable/index.html) – La fuente oficial para todo lo relacionado con NumPy. Este recurso cubre toda la funcionalidad de la biblioteca.
    - [Stack Overflow](https://stackoverflow.com/) – Es el centro de preguntas y respuestas para desarrolladores. Está lleno de soluciones a problemas diversos en desarrollo de software, y seguramente hay alguna relacionada con tu duda.
    - [ChatGPT](https://chat.openai.com/) – ChatGPT es muy bueno explicando código, aunque puede cometer errores. Lo mejor es verificar el código que genera antes de usarlo. Puedes preguntar: “¿Puedes explicarme el siguiente código? {tu código aquí}” y continuar con preguntas de seguimiento. Evita copiar y pegar directamente; en su lugar, usa solo lo que podrías reproducir por tu cuenta con esfuerzo razonable.

Recuerda, no necesitas aprender todas las funciones de memoria desde el principio.

Lo más importante es preguntarte constantemente:
“¿Qué quiero hacer con los datos?”

Empieza por responder esa pregunta y luego practica encontrando el código que lo hace posible.

¡Vamos a comenzar!

## 1. Importar NumPy
Para comenzar a usar NumPy, el primer paso es importarlo.

La forma más común (y la que deberías usar) es importar NumPy con la abreviatura np.

Si ves las letras np en algún lugar relacionado con aprendizaje automático o ciencia de datos, probablemente se estén refiriendo a la biblioteca NumPy.

In [77]:
import numpy as np
print(np.__version__)

2.3.5


## 2. Tipos de datos y atributos

>**Nota**: Es importante recordar que el tipo principal en NumPy es `ndarray`. Incluso los arreglos que parecen diferentes siguen siendo `ndarray`. Esto significa que una operación que haces sobre un arreglo funcionará también sobre otro.

In [78]:
# Array unidimensional, también conocido como vector
a1 = np.array([1, 2, 3])
a1

# Array bidimensional, también conocido como matriz
a2 = np.array([[1, 2, 3],
               [1, 2, 4]])
print(a2)
# Array multidimensional, también conocido como matriz
a3 = np.array([[[1, 2, 3], 
                [1, 2, 4], 
                [1, 2, 5]],
                [[1, 3, 5], 
                 [3, 6, 9], 
                 [3, 3, 4]]])
print(a3)

[[1 2 3]
 [1 2 4]]
[[[1 2 3]
  [1 2 4]
  [1 2 5]]

 [[1 3 5]
  [3 6 9]
  [3 3 4]]]


In [79]:
print(a1.shape, a1.ndim, a1.dtype, a1.size, type(a1))
print(a2.shape, a2.ndim, a2.dtype, a2.size, type(a2))
# .shape nos indica el numero de filas y columnas de nuestra matriz
print(a3.shape, a3.ndim, a3.dtype, a3.size, type(a3))

(3,) 1 int64 3 <class 'numpy.ndarray'>
(2, 3) 2 int64 6 <class 'numpy.ndarray'>
(2, 3, 3) 3 int64 18 <class 'numpy.ndarray'>


In [80]:
a1

array([1, 2, 3])

In [81]:
a2

array([[1, 2, 3],
       [1, 2, 4]])

In [82]:
a3

array([[[1, 2, 3],
        [1, 2, 4],
        [1, 2, 5]],

       [[1, 3, 5],
        [3, 6, 9],
        [3, 3, 4]]])

### Anatomía de un array

<img src="https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/images/numpy-anatomy-of-an-array-updated.png?raw=1" alt="anatomy of a numpy array"/>

Términos clave:

* **Arreglo** (Array) – Una lista de números, puede ser multidimensional.
* **Escalar** (Scalar) – Un solo número (por ejemplo, `7`).
* **Vector** – Una lista de números con una sola dimensión (por ejemplo, `np.array([1, 2, 3])`).
* **Matriz** (Matrix) – Una lista (generalmente) multidimensional de números (por ejemplo, `np.array([[1, 2, 3], [4, 5, 6]])`).

## 3. Creación de arrays

* `np.array()`
* `np.ones()`
* `np.zeros()`
* `np.random.rand(5, 3)`
* `np.random.randint(10, size=5)`
* `np.random.seed()` - pseudo random numbers

In [83]:
simple_array = np.array([1, 2, 3])
print(simple_array)

ones = np.ones((2, 3, 4)) # A ones hay que pasarle el shape enforma de tupla
print(ones)
print(ones.astype(int))

zeros = np.zeros((5, 3, 3))
print(zeros)

[1 2 3]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [84]:
zeros.dtype

dtype('float64')

In [85]:
range_array = np.arange(0, 10, 2)
print(range_array)

[0 2 4 6 8]


In [86]:
# Crear array de numeros aleatorios
random_array = np.random.randint(10, size = (5, 3))
print(random_array)

[[9 4 3]
 [0 3 5]
 [0 2 3]
 [8 1 3]
 [3 3 7]]


In [87]:
np.random.random((5, 3))

array([[0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561],
       [0.77423369, 0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 , 0.61209572],
       [0.616934  , 0.94374808, 0.6818203 ]])

In [88]:
np.random.seed((0))
np.random.rand(5, 3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

NumPy utiliza números pseudoaleatorios, lo que significa que los números parecen aleatorios, pero en realidad no lo son: están predeterminados.

Para mantener la consistencia, puede que quieras que los números aleatorios que generas se mantengan iguales a lo largo de tus experimentos.

Para lograr esto, puedes usar [`np.random.seed()`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html).

Lo que hace esta función es decirle a NumPy:
“Quiero que generes números aleatorios, pero que estén alineados con esta semilla.”

Cuando se establece `np.random.seed()`, cada vez que ejecutes la celda, se generarán los mismos números aleatorios.

¿Y si no se establece `np.random.seed()`?

Cada vez que ejecutes la celda, aparecerá un nuevo conjunto de números aleatorios.

Veámoslo en acción nuevamente. Para mantener la consistencia, vamos a establecer la semilla aleatoria en 0.

Como se ha establecido `np.random.seed(0)`, los números aleatorios generados son los mismos que en cualquier otra celda donde se haya usado esa misma semilla.

Establecer `np.random.seed()` no es estrictamente necesario, pero es útil para mantener los números consistentes a lo largo de tus experimentos.

Por ejemplo, supongamos que quieres dividir tus datos aleatoriamente en conjuntos de entrenamiento y prueba para un proyecto de machine learning.

Cada vez que hagas la división aleatoria, podrías obtener filas diferentes en cada conjunto.

Si compartes tu trabajo con otra persona, ellos también obtendrán filas diferentes.

Establecer `np.random.seed()` garantiza que siga habiendo aleatoriedad, pero hace que esa aleatoriedad sea repetible.
De ahí el término números pseudoaleatorios.

### ¿Qué valores únicos hay en el array a3?

Ahora que has visto varias formas de crear arrays, como ejercicio, intenta descubrir qué función de NumPy podrías usar para encontrar los valores únicos dentro del arreglo a3.

In [ ]:
valores_unicos = np.unique(a3)
print(valores_unicos)

[1 2 3 4 5 6 9]


[1 2 3 4 5 6 9]


## 4. Visualización de arrays y matrices (indexación)

Recuerda que, como los arrays y las matrices son ambos del tipo `ndarray`, pueden visualizarse de formas similares.

Vamos a revisar nuevamente nuestros 3 arrays.

In [ ]:
a1[0]

np.int64(1)

In [ ]:
a2[0]

array([1, 2, 3])

In [ ]:
a3[0]

array([[1, 2, 3],
       [1, 2, 4],
       [1, 2, 5]])

Las formas de los arrays siempre se expresan en el formato `(fila, columna, n, n, n...)`, donde `n` representa dimensiones adicionales opcionales.

In [ ]:
# Obtener los primeros 2 valores de las primeras 2 filas de ambos arreglos en a3
a3[(1, 2)]

array([3, 3, 4])

Los arreglos de NumPy se imprimen de afuera hacia adentro. Esto significa que el número que aparece al final de la forma (shape) es el que se muestra primero, y el número que aparece al inicio de la forma se muestra al final.

In [ ]:
# Obtener solo los primeros 4 números de cada vector individual

La forma del array `a4` es (2, 3, 4, 5), lo que significa que se muestra de la siguiente manera:

* Array más interno = tamaño 5
* El siguiente array = tamaño 4
* El siguiente array = tamaño 3
* Array más externo = tamaño 2

## 5. Manipulación y comparación de arrays

* Aritmética
    * `+`, `-`, `*`, `/`, `//`, `**`, `%`
    * `np.exp()`
    * `np.log()`
    * [Producto punto](https://www.mathsisfun.com/algebra/matrix-multiplying.html) - `np.dot()`
    * Broadcasting
* Agregación
    * `np.sum()` - más rápido que `.sum()` de Python para arrays de NumPy
    * `np.mean()`
    * `np.std()`
    * `np.var()`
    * `np.min()`
    * `np.max()`
    * `np.argmin()` - encuentra el índice del valor mínimo
    * `np.argmax()` - encuentra el índice del valor máximo
    * Estas funciones funcionan en todos los `ndarray`
        * `a4.min(axis=0)` --  también puedes usar axis
* Reformar
    * `np.reshape()`
* Transponer
    * `a3.T`
* Operadores de comparación
    * `>`
    * `<`
    * `<=`
    * `>=`
    * `x != 3`
    * `x == 3`
    * `np.sum(x > 3)`

### Aritmética

In [ ]:
a1

array([1, 2, 3])

In [ ]:
ones = np.ones(3)
print(ones)

[1. 1. 1.]


In [ ]:
# Sumar 2 arrays
suma = a1 + ones
print(suma)

[2. 3. 4.]


In [ ]:
a1 * a2

array([[ 1,  4,  9],
       [ 1,  4, 12]])

In [ ]:
a2

array([[1, 2, 3],
       [1, 2, 4]])

In [ ]:
a3

array([[[1, 2, 3],
        [1, 2, 4],
        [1, 2, 5]],

       [[1, 3, 5],
        [3, 6, 9],
        [3, 3, 4]]])

In [ ]:
a2 .* a3

SyntaxError: invalid syntax (2000345144.py, line 1)

### Broadcasting

- ¿Qué es broadcasting?

    - Broadcasting es una característica de NumPy que permite realizar una operación a través de múltiples dimensiones de datos sin replicar los datos. Esto ahorra tiempo y espacio. Por ejemplo, si tienes un array de 3x3 (A) y quieres sumar un array de 1x3 (B), NumPy sumará la fila de B a cada fila de A.

- Reglas de Broadcasting
    1. Si los dos arrays difieren en su número de dimensiones, la forma del que tiene menos dimensiones se rellena con unos en el lado izquierdo.
    2. Si las formas de los dos arrays no coinciden en alguna dimensión, el array con forma igual a 1 en esa dimensión se expande para coincidir con la otra forma.
    3. Si en alguna dimensión los tamaños no coinciden y ninguno es igual a 1, se genera un error.
    
    
**La regla de broadcasting:**
Para que se pueda aplicar broadcasting, el tamaño de los ejes finales de ambos arrays en una operación debe ser del mismo tamaño o uno de ellos debe ser igual a 1.

También puedes calcular el logaritmo o el exponencial de un array usando las funciones `np.log()` y `np.exp()`.

In [ ]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

### Agregación

Agregación - reunir elementos, hacer algo similar sobre varios elementos.

In [ ]:
sum(a1)

np.int64(6)

In [ ]:
np.sum(a1)

np.int64(6)

**Consejo**: Usa `np.sum()` de NumPy para arrays de NumPy y `sum()` de Python para listas de Python.

In [ ]:
massive_array = np.random.random(100000)
print(massive_array)

[0.0871293  0.0202184  0.83261985 ... 0.75389358 0.10964897 0.63814993]


In [ ]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)


9.63 ms ± 956 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
62.7 μs ± 8.14 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Observa que `np.sum()` es más rápido en el array de NumPy (`numpy.ndarray`) que `sum()` de Python.

Ahora probemos con una lista de Python.

In [ ]:
import random
massive_list = [random.randint(0,10) for _ in range(100000)]
len(massive_list), type(massive_list)


(100000, list)

In [ ]:
massive_list[:10]

[5, 4, 8, 0, 6, 6, 0, 9, 5, 8]

In [ ]:
%timeit massive_list()

`np.sum()` de NumPy sigue siendo rápido, pero `sum()` de Python es más rápido cuando se usa con listas de Python.

In [91]:
a2

array([[1, 2, 3],
       [1, 2, 4]])

In [ ]:
# Encuentra la media


In [ ]:
# Encuentra el max
np.max(a2)

In [ ]:
# Encuentra el min
np.min(a2)

np.int64(4)

In [ ]:
# Encuentra la desviación estándar
np.std(a2), np.sqrt

np.float64(1.0671873729054748)

In [94]:
# Encuentra la varianza
np.var(a2)

np.float64(1.1388888888888888)

**¿Qué es la media?**

La media es lo mismo que el promedio. Puedes encontrar el promedio de un conjunto de números sumándolos y dividiéndolos entre la cantidad total de elementos.

**¿Qué es la desviación estándar?**

La [desviación estándar](https://www.mathsisfun.com/data/standard-deviation.html) es una medida de qué tan dispersos están los números.

**¿Qué es la varianza?**

La [varianza](https://www.mathsisfun.com/data/standard-deviation.html) es el promedio de las diferencias al cuadrado respecto a la media. Indica la variabilidad de un conjunto de datos respecto a su media.

Para calcularla:
1. Calcula la media.
2. Para cada número, réstale la media y eleva el resultado al cuadrado.
3. Encuentra el promedio de esas diferencias al cuadrado.

In [95]:
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

print(np.var(high_var_array), np.var(low_var_array), np.mean(low_var_array))

4296133.472222221 8.0 6.0


In [96]:
np.std(high_var_array), np.std(low_var_array)


(np.float64(2072.711623024829), np.float64(2.8284271247461903))

### Reshaping

In [101]:
a2

array([[1, 2, 3],
       [1, 2, 4]])

In [102]:
a2.shape

(2, 3)

In [103]:
a2+ a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [106]:
a2.reshape(2, 3, 1) + a3

array([[[ 2,  3,  4],
        [ 3,  4,  6],
        [ 4,  5,  8]],

       [[ 2,  4,  6],
        [ 5,  8, 11],
        [ 7,  7,  8]]])

In [105]:
a3.shape

(2, 3, 3)

### Transponer

Una transposición invierte el orden de los ejes.

Por ejemplo, un array con forma `(2, 3)` se convierte en `(3, 2)`.

In [107]:
a2.shape

(2, 3)

In [108]:
a2.T

array([[1, 1],
       [2, 2],
       [3, 4]])

In [109]:
a2.transpose()

array([[1, 1],
       [2, 2],
       [3, 4]])

In [110]:
matrix = np.random.random(size=(5, 3, 3))
matrix 

array([[[0.0871293 , 0.0202184 , 0.83261985],
        [0.77815675, 0.87001215, 0.97861834],
        [0.79915856, 0.46147936, 0.78052918]],

       [[0.11827443, 0.63992102, 0.14335329],
        [0.94466892, 0.52184832, 0.41466194],
        [0.26455561, 0.77423369, 0.45615033]],

       [[0.56843395, 0.0187898 , 0.6176355 ],
        [0.61209572, 0.616934  , 0.94374808],
        [0.6818203 , 0.3595079 , 0.43703195]],

       [[0.6976312 , 0.06022547, 0.66676672],
        [0.67063787, 0.21038256, 0.1289263 ],
        [0.31542835, 0.36371077, 0.57019677]],

       [[0.43860151, 0.98837384, 0.10204481],
        [0.20887676, 0.16130952, 0.65310833],
        [0.2532916 , 0.46631077, 0.24442559]]])

Para arrays más grandes, el valor por defecto de una transposición es intercambiar el primer y el último eje.

Por ejemplo, `(5, 3, 3)` → `(3, 3, 5)`.

In [111]:
matrix.shape

(5, 3, 3)

In [112]:
matrix.T

array([[[0.0871293 , 0.11827443, 0.56843395, 0.6976312 , 0.43860151],
        [0.77815675, 0.94466892, 0.61209572, 0.67063787, 0.20887676],
        [0.79915856, 0.26455561, 0.6818203 , 0.31542835, 0.2532916 ]],

       [[0.0202184 , 0.63992102, 0.0187898 , 0.06022547, 0.98837384],
        [0.87001215, 0.52184832, 0.616934  , 0.21038256, 0.16130952],
        [0.46147936, 0.77423369, 0.3595079 , 0.36371077, 0.46631077]],

       [[0.83261985, 0.14335329, 0.6176355 , 0.66676672, 0.10204481],
        [0.97861834, 0.41466194, 0.94374808, 0.1289263 , 0.65310833],
        [0.78052918, 0.45615033, 0.43703195, 0.57019677, 0.24442559]]])

In [113]:
matrix.T.shape

(3, 3, 5)

In [ ]:
# Comprueba si la forma invertida es igual a la forma de la transpuesta.
matrix.T.shape

In [ ]:
# Comprueba si los primeros y últimos ejes están intercambiados.

Puedes ver formas más avanzadas de transposición en la documentación de NumPy en [`numpy.transpose`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html).

### Producto punto

Las dos reglas principales para recordar sobre el producto punto son:

1. Las **dimensiones internas** deben coincidir:
  * `(3, 2) @ (3, 2)` no funcionará
  * `(2, 3) @ (3, 2)` funcionará
  * `(3, 2) @ (2, 3)` funcionará
  
2. La matriz resultante tiene la forma de las **dimensiones externas**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

**Nota:** En NumPy, `np.dot()` y `@` pueden usarse para lograr el mismo resultado en arrays de 1-2 dimensiones. Sin embargo, su comportamiento comienza a diferir en arrays con 3 o más dimensiones.

In [115]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(3, 3))
mat2 = np.random.randint(10, size=(3, 2))

mat1.shape, mat2.shape


((3, 3), (3, 2))

In [116]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]], dtype=int32)

In [117]:
mat2

array([[4, 7],
       [6, 8],
       [8, 1]], dtype=int32)

### Operadores de comparación

Descubrir si un array es mayor, menor o igual a otro.

In [118]:
a1

array([1, 2, 3])

In [119]:
a2

array([[1, 2, 3],
       [1, 2, 4]])

In [120]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [121]:
a2[a1>a2]

array([], dtype=int64)

In [122]:
a1 == a2

array([[ True,  True,  True],
       [ True,  True, False]])

## 6. Ordenar arrays

* [`np.sort()`](https://numpy.org/doc/stable/reference/generated/numpy.sort.html) - ordena valores en una dimensión específica de un array.
* [`np.argsort()`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) - devuelve los índices para ordenar el array en un eje dado.
* [`np.argmax()`](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html) - devuelve el índice/índices que dan el valor más alto a lo largo de un eje.
* [`np.argmin()`](https://numpy.org/doc/stable/reference/generated/numpy.argmin.html) - devuelve el índice/índices que dan el valor más bajo a lo largo de un eje.

In [123]:
random_array

array([[9, 4, 3],
       [0, 3, 5],
       [0, 2, 3],
       [8, 1, 3],
       [3, 3, 7]], dtype=int32)

In [124]:
np.sort(random_array)

array([[3, 4, 9],
       [0, 3, 5],
       [0, 2, 3],
       [1, 3, 8],
       [3, 3, 7]], dtype=int32)

In [125]:
np.argsort(random_array)

array([[2, 1, 0],
       [0, 1, 2],
       [0, 1, 2],
       [1, 2, 0],
       [0, 1, 2]])

In [126]:
np.argmin(random_array)

np.int64(3)

In [127]:
np.argmax(random_array)

np.int64(0)

In [128]:
random_array

array([[9, 4, 3],
       [0, 3, 5],
       [0, 2, 3],
       [8, 1, 3],
       [3, 3, 7]], dtype=int32)

In [129]:
# Maximo por fila
np.argmax(random_array, axis = 1)

array([0, 2, 2, 0, 2])

2